# **Meaning of reshape in numpy**
It simply means that you are not sure about what number of rows or columns you can give and you are asking numpy to suggest 
a number of column or rows to get reshaped in.

**1)** What does reshape((-1,1) mean?

**2)** What does reshape((1,-1) mean? 

In [2]:
import numpy as np
b = np.arange(10).reshape((-1,1)) #Unknown Rows, Column is 1
print(b)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [3]:
b = np.arange(10).reshape((1,-1))#Unknown Column, Row is 1
print(b)

[[0 1 2 3 4 5 6 7 8 9]]


In [4]:
import numpy
a = numpy.matrix([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Without reshaping  -> ")
print(a)
b = numpy.reshape(a, -1)
print("HERE We don't know about what number we should give to col")
print("Reshaping as (a,-1)")
print(b)
c = numpy.reshape(a, (-1,2))
print("HERE We just know about number of columns")
print("Reshaping as (a,(-1,2))")
print(c)
d = numpy.reshape(a, (2,-1))
print("HERE We just know about number of rows")
print("Reshaping as (a,(2,-1))")
print(d)

Without reshaping  -> 
[[1 2 3 4]
 [5 6 7 8]]
HERE We don't know about what number we should give to col
Reshaping as (a,-1)
[[1 2 3 4 5 6 7 8]]
HERE We just know about number of columns
Reshaping as (a,(-1,2))
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
HERE We just know about number of rows
Reshaping as (a,(2,-1))
[[1 2 3 4]
 [5 6 7 8]]
